name: Test Workflow
on: [push,workflow_dispatch]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get github details
        run: echo " {{ toJSON(github.event) }} "
      - name: Get code
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm install
      - name: install Jest and Jest Supertest
        run: npm install --save-dev jest supertest
      - name: Run test
        run: npm test